### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FMDatabaseQueue

### ISSUE THREAD

**Issue by yetunnaing18121996** [tekartik/sqflite#673] opened 2021-07-20 05:10 UTC
I use M1 Macbook Air ,
flutter sdk 2.2.3
sqflite: ^2.0.0+3
XCode : 12.5
When I build flutter ios app from XCode,
it says me like that.

##Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FMDatabaseQueue", referenced from:
      objc-class-ref in SqflitePlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
how can I solved this?

**Comment by alextekartik** [comment] 2021-07-20 08:17
Duplicate of #540

**Closed by alextekartik** 2021-07-20 08:17 UTC
