### ISSUE TITLE
Multi-Isolate access to Sqflite (iOS)

### ISSUE THREAD

**Issue by prefanatic** [tekartik/sqflite#168] opened 2019-03-06 20:29 UTC
Hi,

I am encountering deadlock behavior when attempting to use sqflite in an environment that contains two isolates.  The first isolate (foreground, in the case of Flutter) works perfectly fine.  Upon spinning up a background Flutter engine, and then attempting to open a database, sqflite hangs.  This behavior is only encountered on iOS, and not on Android.

When accessing the database on the background isolate, I've traced the code down to the following:
https://github.com/tekartik/sqflite/blob/master/sqflite/ios/Classes/SqflitePlugin.m#L427

After inserting the initial `BEGIN EXCLUSIVE` statement in the queue, nothing else happens, and the transaction seems to lock.  Using `Sqflite.setDebugModeOn` was not sufficient enough to discover this deadlock, as the print statement for the execute seems to be after where the deadlock occurs.

I've also attempted to ignore the version checks by omitting a version for `openDatabase` on a background isolate, which does proceed to pass the initial deadlock encountered otherwise, but then the first transaction issued after the database opens locks anyways.

On Android, none of this occurs.  The background isolate is capable of utilizing sqflite to access and query the database without issue.

~~Unfortunately, I encountered this bug on code I am unable to share.  I'm currently working on creating a small project that can be used to reproduce this on both platforms, however it requires a bit of setup to get the background execution part - I'm hoping I can share this tomorrow (Thursday, 3/7)~~
Reproducible sample can be found here: https://github.com/prefanatic/sqflite_isolate_bug

**Comment by alextekartik** [comment] 2019-03-07 00:46
Thanks for the note. I have personally not tested with isolate and I am not an ios expert. SQLite has itself some threading rules and I'm not sure how everything (+ plugin) plays together. I'll take a look. Indeed some reproducable code would help (I know it is a pain)

**Comment by prefanatic** [comment] 2019-03-07 15:19
Hey @alextekartik,

I've pushed a reproducible sample with iOS here: https://github.com/prefanatic/sqflite_isolate_bug

Currently working on the Android portion.

Thanks ahead of time for taking a look!

**Comment by alextekartik** [comment] 2019-03-08 00:08
Thanks for the reproducible project. I indeed encounter a lock but sometimes simply a crash...This issue seems to be discussed here https://github.com/flutter/flutter/issues/21925

It seems that currently iOS plugin do not support background isolate call. I'll try again when their fix landed (it seems one scenario was clearly around supporting sqlite)

**Comment by prefanatic** [comment] 2019-03-08 00:15
Oh, I'm sorry - I should have mentioned, this requires running Flutter either on the `dev` or `master` channel.  The background isolate's support for plugins on iOS landed in the last few weeks, and are available in those channels.

**Comment by alextekartik** [comment] 2019-03-08 01:27
Ok It seems indeed that the extra operation queue I added causes the deadlock. I removed it (one goal was to avoid any work in the main thread but I guess it broke with isolates) and it seems to work. I can run the background isolate once in your test program then run the foreground multiple times. Before it was hanging. I cannot run the background isolate twice as it complains about `Duplicate plugin key: com.tekartik.sqflite.SqflitePlugin'` in your initialization code so I guess some tweaks are needed here.

I published a 1.1.3-dev version that you need to specify explicitly. Let me know if it works for you

**Comment by prefanatic** [comment] 2019-03-08 15:15
That did it!  Thank you so much - both the demo app & the original app encountering this bug are experiencing the same behavior between Android & iOS on the background isolate.

**Comment by alextekartik** [comment] 2019-03-08 17:37
I published 1.1.3 version (no more -dev). I could not manage yet to add a test case in my example application. Isolate and plugin still look complex to me (especially on the registration side) so will wait to get more information. So far your simple test app is perfect! Thanks

**Closed by alextekartik** 2019-03-08 17:37 UTC
