### ISSUE TITLE
Windows support planned?

### ISSUE THREAD

**Issue by robert-virkus** [tekartik/sqflite#356] opened 2020-01-18 17:55 UTC
@alextekartik, thanks for your great work with SQFlite! 

Do you plan to support Windows desktop and what are the challenges for that?

**Comment by alextekartik** [comment] 2020-01-20 08:11
Yes. Windows Desktop is not even alpha yet and no official flutter plugins supports Windows yet so I'd rather wait for the plugin API to stabilize and Windows support getting to alpha level quality like MacOS is now.

**Comment by romanjamesmirov** [comment] 2020-01-22 20:26
@alextekartik Is it just not that viable to write SQFlite for the current Windows shell that they have? God I wish I was able to learn what it takes to extend support to Windows and help. I don't know what language it requires even. And yes, thanks for your great work.

**Comment by stuartmorgan** [comment] 2020-02-03 20:39
> Is it just not that viable to write SQFlite for the current Windows shell that they have?

It is viable, but per [the current instructions](https://github.com/google/flutter-desktop-embedding/tree/master/plugins#writing-your-own-plugins):
>> Keep in mind the notes about API stability on the Flutter desktop page linked above. On platforms where the plugin API is still unstable, or where `flutter` tool support doesn't exist yet, you should expect to need to substantially change plugins written now as the APIs evolve.

So if it's written as a plugin now it might need to be partially, or even completely, rewritten at a later point.

> God I wish I was able to learn what it takes to extend support to Windows and help. I don't know what language it requires even.

Currently C++. The instructions above have an example plugin for Windows if you want to try implementing this yourself.

The other possibility would be to implement it using FFI rather than as a plugin (#210), thus bypassing the issue of plugin API instability; in that case you would use Dart. However, there isn't tooling support for FFI-based packages on Windows yet either, so setting up in an app using it would be manual as with the current plugin situation.

**Comment by alextekartik** [comment] 2020-02-04 08:17
Thanks @stuartmorgan for juming in. For your information Simon Binder has done a good job on sqlite and ffi so far in moor_ffi. I was able to implement a quick stub that allows running sqflite unit test on windows (even bunding the sqlite.dll for windows in the package - not sure if that is allowed): https://github.com/tekartik/sqflite_more/tree/master/sqflite_ffi_test

Right now using ffi, every action are in the main isolate but it should be easy to create an isolate for this. My main issue that prevents using sqflite and ffi is for HotRestart. Similar to this, on Android we have a similar issue if you exit and restart and app: currently the native side is not unloaded while the dart code is unloaded. Not sure if that could happen on windows too. This means that we have some unknown state on the native side. On sqlite that could mean that if there was a transaction in progress, you're stuck, sqlite will complain that the database is locked.

@stuartmorgan Do you know if there is a way to save global values from dart on the native that won't clear on hotrestart that the app can read again (for example to cancel the pending transaction of an existing sqlite connection)?

**Comment by stuartmorgan** [comment] 2020-02-04 17:26
I'm afraid I'm not familiar with the internals of hot restart, so I'm not sure. It sounds like that may be a more general problem than hot restart though (e.g., what happens if an app crashes during a transaction)?

**Comment by alextekartik** [comment] 2020-02-04 17:37
SQLite handles crashes even in transaction quite well (when the application crashes and quits, all sqlite connections are closed and uncommited data will be ignored when re-opening the database). sqflite has some workaround for hotrestart on mac/ios/android by maintaining a cache of the open databases on the native side (so that it won't get cleared on hot restart and so that some cleanup can be done to prevent locks). I'm not sure how this can be done with ffi only.

**Comment by stuartmorgan** [comment] 2020-02-04 17:44
Ah, now I see what you mean. Sorry, I misunderstood the specific issue.

I don't know if there's a better option, but one possibility would be to implement that code in C (or C++ with a C interface) once, and FFI to that code as well. That could either be a wrapper around the SQLite calls, as you are doing in the plugins currently, or a separate library on the side.

**Comment by alextekartik** [comment] 2020-02-04 17:56
> but one possibility would be to implement that code in C (or C++ with a C interface) once to use across all platforms, and FFI to that code as well

I like this idea. A kind of native memory cache that dart code can re-use across hot-restart sessions.

**Comment by alextekartik** [comment] 2020-02-06 22:12
@romanjamesmirov I copied the necessary windows file to a [test app](https://github.com/tekartik/sqflite_more/tree/master/sqflite_test_app) and was able to run sqflite on windows. It is not using the plugin mechanism and hot restart could fail if a transaction was in progress:

**Comment by alextekartik** [comment] 2020-03-13 15:31
sqflite_common_ffi v1.0.0 has been published allowing using ffi on the desktop. It is based on moor_ffi (!) that provides a nice wrapper around sqlite libraries.

However once plugin are well supported on Windows and linux, it will be added to sqflite plugin

**Comment by talnetd** [comment] 2020-04-23 04:15
Any update with this planning? I am trying SQFLite_common_ffi but it is only good for testing.

**Comment by alextekartik** [comment] 2020-04-23 09:47
Flutter team has not release any windows plugin yet and windows support is not fully mature yet. sqlifte_common_ffi should work on Windows (flutter and vm). You could use databaseFactory on mobile and databaseFactoryFfi on windows and linux.

>  it is only good for testing

Besides my own warning, what are you missing from it? One issue should be potential database lock if hot restart was made during a transaction. Did you encounter any other issue with it?  (I mainly work on Linux and don't test on Windows very often).

**Comment by talnetd** [comment] 2020-04-23 21:23
Sorry for immature remark about "only good". What I have been missing was databaseFactoryFfi and I will try to check again with it. Since I have been very active with the Embedded window project, I will try to report any problem I encounter.

Thanks for the point out appreciate it.

**Comment by ReniDelonzek** [comment] 2020-06-05 13:08
I performed the tests based on the implementation of @hhtokpinar, as discussed [here] (https://github.com/hhtokpinar/sqfEntity/issues/59) and my results were as follows:

- At first, all sqlite features behaved well.
- The path of sqlite3.dll even worked in debug mode, but it was broken in the release version (for obvious reasons).
- It is inappropriate to keep sqlite3.dll in the middle of the code, there are ways to include a more suitable ffi executable with the flutter, however, there is no documentation of this for windows. Discussions [here] (https://flutter.dev/docs/development/platform-integration/c-interop) and [here] (https://github.com/flutter/flutter/issues/33227)

I made the necessary changes to the code (although there is still no fully correct solution, possibly in the future it could be changed) and sent the PR

**Comment by devjeff** [comment] 2020-06-07 21:30
Hey, what's the current status with the PR? It would be really cool to have a working solution that can be executed in any directory. At the moment, the sqflite_ffi code plugin tries to load the the sqlite3.dll via the information stored in the .packages file.

**Comment by Airbus5717** [comment] 2020-07-01 04:08
Feature Suggestion : - Compiling  for Windows from Linux .

**Comment by alextekartik** [comment] 2020-07-01 08:13
I'm sorry I will close this issue since it is going in too many directions. I created a document here https://github.com/tekartik/sqflite/blob/develop/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md that shows how to support flutter windows/linux applications.

@Airbus5717 currently sqlite.c is not compiled for windows and linux, the solution is using ffi and existing shared libraries. And whether windows code can be compiled on Linux, I have no idea at this point and that is not sqflite specific, you should ask the flutter team.

@devjeff @ReniDelonzek Windows/Linux supports is done using ffi using the excellent [`moor_ffi`](https://pub.dev/packages/moor_ffi) packages. How the sqlite3.dll/.so file is loaded can be customized (you can even bring your own library). sqflite_common_ffi has one convenient way during development but you have to look at moor_ffi documention for more information. Also as I said in the PR, sqflite_common_ffi is not a flutter package, it also works on DartVM.

Things will likely change in the future but it will only involve the initialization steps. Linux supports just landed in the dev branch, I will try to support it the best way I can (and I do all my development on Linux).

Thanks!

**Closed by alextekartik** 2020-07-01 08:13 UTC

**Comment by iampopal** [comment] 2021-05-19 00:42
Whats update about this issue, when will i able to use one package for Windows, Android, and Ios

**Comment by jinfagang** [comment] 2021-05-29 15:29
Do u guys able to run `flutter build windows` generated exe file? It can not retive data from sql, but `flutter run` seems works fine.

**Comment by alextekartik** [comment] 2021-05-31 06:31
@jinfagang 

> It can not retive data from sql

Can you explain more that you mean by "it can not retrieve"?. Can you open the database? Do you have some (crash) logs? Did you copy the dll along with the executable as suggested here: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi#windows

**Comment by jinfagang** [comment] 2021-05-31 07:10
@alextekartik  It's indeed an issue but I found a solution of it.

I build release it can not get data from database, the issue is it can not foun dynamic library of sqlite3.so (sqlite.dll on windows). I directly downloaded a dll version from sqlite website and place it in the same folder of my build release generated exe, it now can run.

So, my guess is somewhat linking way broken on flutter or that ffi, casued unable to get the .so or .dll. Although it can resolved by manually copied, but seems not a good way.

Any workaround and suggestion?

**Comment by alextekartik** [comment] 2021-05-31 07:39
Copying dll is a manual operation (as some user might want to use a different one).

**Comment by jinfagang** [comment] 2021-06-02 03:36
@alextekartik Yeah, still not know why `flutter run` can run but not `flutter build release`, doesn't they both need dynamic lib?

**Comment by ayoubzulfiqar** [comment] 2023-08-23 10:47
# SQFlite on Windows

```dart
flutter pub add sqflite_common_ffi
```

## Step - 1
Remember to Download Windows Binary
[Download SQLite DDL FIle](https://www.sqlite.org/download.html)

## Path
Add the DLL File to this path
![sqlpath](https://github.com/tekartik/sqflite/assets/78419552/64f36090-bdaf-4dd4-a577-3d927f015c69)

## Code 
```dart
class SQFLite {
  Database? _database;

  Future<Database> get database async {
    if (_database != null) {
      return _database!;
    }
    _database = await initWinDB();
    return _database!;
  }

  Future<Database> initWinDB() async {
    sqfliteFfiInit();
    final databaseFactory = databaseFactoryFfi;
    return await databaseFactory.openDatabase(
      inMemoryDatabasePath,
      options: OpenDatabaseOptions(
        onCreate: _onCreate,
        version: 1,
      ),
    );
  }

// based on what type of data you want to add your Table
  Future<void> _onCreate(Database database, int version) async {
    final db = database;
    await db.execute(""" CREATE TABLE IF NOT EXISTS users(
              id INTEGER PRIMARY KEY,
              name TEXT,
              email TEXT,
              password INTEGER,
              phoneNumber INTEGER
            )
  """);
  }
}
```
## Initialization
Either you can write this in the main function or if you  are working on separate file You can add it inside initState()

```dart
  void initState() {
    super.initState();
    WidgetsFlutterBinding.ensureInitialized();
    helper.initWinDB();
  }
```

### [Github Code](https://gist.github.com/ayoubzulfiqar/ea0c22461075ce708a2abbca433a9744)
