### ISSUE TITLE
my Row has a bigger value so its throwing (Row too big to fit into CursorWindow requiredPos=0, totalRows=1)  

### ISSUE THREAD

**Issue by jk-hub** [tekartik/sqflite#479] opened 2020-07-18 07:44 UTC
please help me out of this (Row too big to fit into CursorWindow requiredPos=0, totalRows=1) ASAP!

**Comment by alextekartik** [comment] 2020-07-18 08:34
I don't know on which platform you are seeing this. On Android there is a 1 MB limit that cannot be changed. See https://stackoverflow.com/questions/5406429/cursor-size-limit-in-android-sqlitedatabase

In general avoid big records and save big records/blobs/images in a dedicated file.

**Comment by alextekartik** [comment] 2020-07-18 08:39
Closing as duplicate of #270

**Closed by alextekartik** 2020-07-18 08:39 UTC

**Comment by CrazyPudding** [comment] 2020-07-23 08:18
But actually, when I upgrade my db, and the old version only has 1 row that with 6 columns contains only text, this problem also happened.

Here is the data and the code I run:

data: [{_id: 1, column1: asgsdfhfh, column2: sjJYNwBiN50Kw5c=, create_time: 2020-07-23 14:52:54, column4: 234562367245346, column5: null}]

and the code:
`_onUpgrade(Database db, int oldVersion, int newVersion) async {
  var list = await db.query(tableName);
}`

The weird thing is that I can get the result before the Error throws when I run with Debug Step Into but only get the Error when let it run normal.

Is something wrong I overlooked? Thanks for your attention.

**Comment by CrazyPudding** [comment] 2020-07-23 08:32
> But actually, when I upgrade my db, and the old version only has 1 row that with 6 columns contains only text, this problem also happened.
> 
> Here is the data and the code I run:
> 
> data: [{_id: 1, column1: asgsdfhfh, column2: sjJYNwBiN50Kw5c=, create_time: 2020-07-23 14:52:54, column4: 234562367245346, column5: null}]
> 
> and the code:
> 
> ```dart
> _onUpgrade(Database db, int oldVersion, int newVersion) async {
>   var list = await db.query(tableName);
> }
> ```
> 
> The weird thing is that I can get the result before the Error throws when I run with Debug `Step Into` but only get the Error when let it run normal.
> 
> Is something wrong I overlooked? Thanks for your attention.

It's worked when I use `db.rawQuery(tableName)` instead of `db.query(tableName)`.

**Comment by alextekartik** [comment] 2020-07-23 10:03
> It's worked when I use db.rawQuery(tableName) instead of db.query('select * from tableName').

I guess you meant: `db.query(tableName)`  instead of `db.rawQuery('select * from tableName')` which are indeed equivalent.

Hard to say what is going wrong since this error typically happen when you have a big row (about 1 MB). What is the size of your database?

**Comment by CrazyPudding** [comment] 2020-07-23 13:29
> I guess you meant: `db.query(tableName)` instead of `db.rawQuery('select * from tableName')` which are indeed equivalent.
> 
> Hard to say what is going wrong since this error typically happen when you have a big row (about 1 MB). What is the size of your database?

 yep, `db.rawQuery('select * from tableName')` worked but `db.query(tableName)`(I'm sorry for for the mistake in my previous description)

My database is only 20kb. 

My case is: When the db upgrade from version 1 to version 2 which just add some new columns, I want to print some logs before the migration and after.

I found this snip of code worked:

```Dart
_onUpgrade(Database db, int oldVersion, int newVersion) async {
    // log 1
    Log.log(await db.rawQuery('select * from tableName'),
        name: 'data in DB before migration');
    if (oldVersion < 2) {
      Log.log('Migrate kong.db from 1 to 2', name: 'DB Migration');
      await migration_1_2(db);
    }
    // log 2
    Log.log(await db.query('tableName'), name: 'data in DB after migration');
  }
```

When the `log 1` and `log 2` use the same function -- `query()` or `queryRaw()`, it's failed. By the way, I'm testing on Android.

**Comment by alextekartik** [comment] 2020-07-23 15:55
Weird indeed. Can try adding this in your main method (before opening the database) to see what is going on:

```dart
import 'package:sqflite_common/sqflite_dev.dart';

await factory.setLogLevel(sqfliteLogLevelVerbose);
```

and view your logs (might need to use adb logcat if the native logs are not visible in the flutter logs). thanks!

**Comment by CrazyPudding** [comment] 2020-07-24 05:01
Hey, I've tried your suggestion. The log just says `Failed to read row 0, column 6 from a CursorWindow which has 1 rows, 6 columns`, maybe it queries data with the old scheme?

I create a simple demo to reproduce this error. If you have time, cloud you pls help me to see if I used it wrong?

The repository is [here](https://github.com/CrazyPudding/row_too_big_demo). thanks for your patient!

**Comment by alextekartik** [comment] 2020-07-24 15:40
@CrazyPudding Thanks for taking the time to write a test app. Unfortunately I could not reproduce your issue in your example (event after doing some changes to force the migration...). Maybe it is because I don't have a database at version 1 with some data...

**Comment by CrazyPudding** [comment] 2020-07-27 06:28
@alextekartik Sorry, maybe I should provide some steps to reproduce the issue.
1. comment `column6`, `column7`, `column8`, `column9` in `db_record.dart` and change the `version` to 1 at `db_util.dart(:32)`. Here we get the scheme at version 1
2. run the app and tap to insert some data
3. uncomment the filed which is commented at step 1 and change the `version` to 2
4. run the app again and tap to insert some data and the issue will be occurred
