### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.

### ISSUE THREAD

**Issue by lizhuoyuan** [tekartik/sqflite#177] opened 2019-03-25 03:36 UTC
```
Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(Unknown Source)
       at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(Unknown Source)
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(Unknown Source)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(Unknown Source)
       at com.tekartik.sqflite.SqflitePlugin$BgResult$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

  sqflite: ^1.1.3

**Comment by mtallenca** [comment] 2019-03-29 00:13
I'm seeing the same trace when my native android app loads a flutter fragment, then the user quickly exits the flutter code and execution is returned to the native app.  sqflite BgResult is called at a time when flutter is no longer attached.

**Comment by alextekartik** [comment] 2019-03-29 07:45
I'm not familiar with this flutter fragment usage. Indeed sqflite runs asynchronously so the result can happen later. Is there any way to "wait" in this scenario or is there a way to reproduce easily this issue?

**Comment by mtallenca** [comment] 2019-03-29 16:24
Super easy to reproduce.  We start an existing Android app that loads a flutter fragment ( https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps). The flutter code is just a sequence of on boarding screens.  Quickly tap "next" through them, the flutter sends a message to native Android that it's done and Android code removes the flutter fragment.  A few milliseconds later, sqflite trys to send a success message on a channel and the flutter code throws an exception because UI is not attached.

We actually aren't using sqflite at the moment, looks like there is a set of packages that get added by the flutter create command.  We will be using sqflite in the future so it would be better to get this fixed instead of just removing the package.

Possible solutions: Flutter's module code allowing channel calls when no UI is attached, or trapping the exception in sqlflite, or I can "wait" - is there a sqflite call that will let me know if any async tasks haven't completed?

**Comment by alextekartik** [comment] 2019-03-29 17:14
In the link you sent, I don't see anything related to sqflite so it seems that you have a package that uses it. So far I don't see what sqflite can do wrong compare to other flutter plugins. Sqflite does not send notification and only respond to request so if a component used in your case send a command while flutter is unloaded, well it should not crash and rather than handling that at the sqflite level (yes of course I could catch all exception when sending a response but no other plugin does that...), I'd rather have this fixed in flutter itself.

It seems some people are having similar issue with other plugins https://github.com/flutter/flutter/issues/28651 and recent flutter have fixed it. Have you tried on master or dev branch?

thanks

**Comment by mtallenca** [comment] 2019-03-29 17:49
Great! Flutter module code has been updated to "allow (not crash)" when a message is sent and UI is not attached.  I'm on beta branch right now looks like 

    @UiThread
    public void invokePlatformMessageResponseCallback(int responseId, ByteBuffer message, int position) {
        this.ensureAttachedToNative(); // <-- this throws an exception
        this.nativeInvokePlatformMessageResponseCallback(this.nativePlatformViewId, responseId, message, position);
    }

has been replaced by 

@UiThread
  public void invokePlatformMessageEmptyResponseCallback(int responseId) {
    if (isAttached()) {
      nativeInvokePlatformMessageEmptyResponseCallback(nativePlatformViewId, responseId);
    } else {
      Log.w(TAG, "Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: " + responseId);
    }
  }

in the master channel...

**Comment by alextekartik** [comment] 2019-03-29 18:07
Perfect, better than a try catch everywhere!

**Closed** 2019-07-19 16:55 UTC

**Comment by jp1017** [comment] 2019-10-29 03:06
Here is another same Q: https://github.com/flutter/flutter/issues/33511, can you help me?  @alextekartik @mtallenca
